name: Build Android
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build upload keystore file
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: release.keystore
          fileDir: android/app
          encodedString: ${{ secrets.KEYSTORE_BASE64 }}

      - name: Build APK
        env:
          NODE_ENV: 'production'
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease

      - name: Build AAB
        env:
          NODE_ENV: 'production'
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          cd android
          chmod +x gradlew
          ./gradlew bundleRelease -Pandroid.bundle=true

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk-release
          path: android/app/build/outputs/apk/release/*.apk

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: aab-release
          path: android/app/build/outputs/bundle/release/*.aab
