name: Release Web
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

jobs:
  boundle:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build assets
        run: pnpm run web:prod

      - name: Archive built content
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: 'web-dist.zip'
          directory: 'dist'

      - name: Upload ZIP
        uses: actions/upload-artifact@v4
        with:
          name: web-release
          path: dist/web-dist.zip

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
