name: Release Web
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

jobs:
  boundle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build assets
        run: pnpm run web:prod

      - name: Upload built content
        uses: actions/upload-artifact@v4
        with:
          name: web-dist
          path: dist/

  deploy-prod:
    name: Deploy via SCP
    runs-on: ubuntu-latest
    needs: boundle

    environment:
      name: krystian-vps

    steps:
      - name: Download built content
        uses: actions/download-artifact@v4
        with:
          name: web-dist
          path: dist

      - name: Display downloaded content
        run: ls -R dist/

      - name: Copy artifact to server
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          target: ${{ secrets.FILES_PATH }}
          source: dist/*
          strip_components: 1
          rm: true
